calceus/config/routes.rb
Rails.application.routes.draw do
  Calceus::Application.routes.draw do
    resources :shoes
  end

  get 'search', to: 'search#search'
  root 'shoes#index'

end

calceus/app/models/shoe.rb
class Shoe
  include Mongoid::Document
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  field :title
  field :photo
  field :link
  field :price
  field :gender
  field :sizes, type: Array, default: []
  field :colors, type: Array, default: []

  validates_presence_of :title
  validates_presence_of :photo
  validates_presence_of :link
  validates_presence_of :price
  validates_presence_of :gender
  validates_presence_of :sizes
  validates_presence_of :colors

  settings index: {
    number_of_shards: 1, 
    number_of_replicas: 0,
    analysis: {
      filter: {
        my_stemmer: {
          type: 'stemmer',
          language: 'bulgarian'
        },
        my_soundex: {
          type: 'phonetic',
          encoder: 'doublemetaphone',
          replace: false
        }
      },
      analyzer: {
        myAnalyzer: {
          type: 'custom',
          tokenizer: 'standard',
          filter: ['standard', 'lowercase', 'my_soundex', 'my_stemmer']
        }
      }
    }
  } do
    mappings dynamic: 'false' do
      indexes :title, analyzer: 'myAnalyzer'
      indexes :colors, analyzer: 'myAnalyzer'
      indexes :gender, analyzer: 'myAnalyzer'
      indexes :price
      indexes :photo
      indexes :link
      indexes :sizes
    end
  end

  def sizes_list=(arg)
    self.sizes = arg.split(',').map(&:strip)
  end

  def sizes_list
    self.sizes.join(', ')
  end

  def colors_list=(arg)
    self.colors = arg.split(',').map(&:strip)
  end

  def colors_list
    self.colors.join(', ').downcase
  end

  def as_indexed_json(options={})
    as_json(except: [:id, :_id])
  end

  def self.more_like_this(shoe)
    black_list = ['спортни', 'обувки', 'ботуши', 'туристически', 'джапанки',
            'апрески', 'футболни', 'платформа', 'сандали', 'дамски', 'кецове',
            'маратонки', 'зимни', 'чехли', 'мъжки', 'балеринки', 'black', 'white',
            'red', 'blue', 'grey']

    filtered_title = shoe.title.mb_chars.downcase.to_s.gsub(/( | \w)(\d)+/, "")
    black_list.each do |word|
      filtered_title = filtered_title.gsub(word, "")
    end

    filtered_title = filtered_title.split(' ').uniq
    filtered_title.shift

    if filtered_title.size <= 2
      minimum_should_match = "100%"
    else
      minimum_should_match = "75%"
    end

    filtered_title = filtered_title.to_s

    __elasticsearch__.search(
      {
        query: {
          bool: {
            filter: {
              match: {
                title: {
                  query: filtered_title,
                  minimum_should_match: minimum_should_match
                }
              }
            },
            should: [
              {
                more_like_this: {
                  fields: ['colors'],
                  docs: [
                    {
                      _index: 'shoes',
                      _type: 'shoe',
                      _id: shoe.id.to_s
                    }
                  ],
                  ids: [shoe.id.to_s]
                }
              },
              {
                more_like_this: {
                  fields: ['gender'],
                  docs: [
                    {
                      _index: 'shoes',
                      _type: 'shoe',
                      _id: shoe.id.to_s
                    }
                  ],
                  ids: [shoe.id.to_s]
                }
              }
            ],
            minimum_should_match: 2
          }
        }
      }
    )
  end

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['title', 'gender', 'colors', 'sizes', 'price'],
            tie_breaker: 0.5,
            analyzer: 'myAnalyzer'
          }
        }
      }
    )
  end
end

calceus/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

calceus/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:q].nil?
      @shoes = []
    else
      @shoes = Shoe.search params[:q]
    end
  end
end

calceus/app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :set_shoe, only: [:show, :edit, :update, :destroy]

  def index
    @shoes = Shoe.limit(10)
  end

  def show
    @similar_shoes = Shoe.more_like_this(@shoe).results.to_a
  end

  def new
    @shoe = Shoe.new
  end

  def edit
  end

  def update
    if @shoe.update(shoe_params)
      redirect_to @shoe, notice: 'Обувките бяха успешно обновени.'
    else
      render :edit
    end
  end

  def create
    @shoe = Shoe.new(shoe_params)

    if @shoe.save
      redirect_to @shoe, notice: 'Обувките бяха успешно създадени.'
    else
      render :new
    end
  end

  def destroy
    @shoe.destroy
    redirect_to shoes_url, notice: 'Обувките бяха успешно изтрити.'
  end

  private
    def set_shoe
      @shoe = Shoe.find(params[:id])
    end

    def shoe_params
      params.require(:shoe).permit(:title, :photo, :link, :price, :sizes, :colors, :gender, :sizes_list, :colors_list)
    end
end

calceus/app/helpers/application_helper.rb
module ApplicationHelper
end

calceus/app/helpers/search_helper.rb
module SearchHelper
end

calceus/app/helpers/shoes_helper.rb
module ShoesHelper
end

calceus/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calceus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

calceus/app/views/search/search.html.erb
<div class="page-header">
  <h1>Търсене на обувки</h1>
</div>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <div class="col-lg-10">
      <%= text_field_tag :q, params[:q], :class => 'form-control' %>
    </div>
    <%= submit_tag "Търси", name: nil, :class => 'btn btn-primary' %>
  </p>
<% end %>

<div class="page-header">
  <h1>Резултати</h1>
  <% unless @shoes.empty? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Модел</th>
          <th>Снимка</th>
          <th>Цена</th>
          <th>Вид</th>
          <th>Размери</th>
          <th>Цветове</th>
          <th>Дистрибутор</th>
        </tr>
      </thead>
      <tbody>
        <% @shoes.each do |shoe| %>
          <tr>
            <td><%= link_to shoe.title.mb_chars.upcase.to_s, controller: "shoes", action: "show", id: shoe._id %></td>
            <td><%= image_tag shoe.photo %></td>
            <td><%= shoe.price %></td>
            <td><%= shoe.gender %></td>
            <td><%= shoe.sizes.join(', ') %></td>
            <td><%= shoe.colors.join(', ').mb_chars.downcase.to_s %></td>
            <td><%= link_to 'Купи', shoe.link %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>Не са намерени резултати.</p>
  <% end %>
</div>

calceus/app/views/shoes/_form.html.erb
<%= form_for @shoe, :html => { :class => "form-horizontal shoe" } do |f| %>

  <% if @shoe.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@shoe.errors.count, "error") %> prohibited this shoe from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @shoe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Модел", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label "Линк към снимка", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :photo, :class => 'form-control' %>
    </div>
    <%=f.error_span(:photo) %>
  </div>
  <div class="form-group">
    <%= f.label "Оригинален линк", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :link, :class => 'form-control' %>
    </div>
    <%=f.error_span(:link) %>
  </div>
  <div class="form-group">
    <%= f.label "Цена", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>
  <div class="form-group">
    <%= f.label "Вид", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :gender, options_for_select(['мъжки','женски']), {}, :class => 'form-control' %>
    </div>
    <%=f.error_span(:gender) %>
  </div>
  <div class="form-group">
    <%= f.label "Размери", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :sizes_list, :class => 'form-control' %>
    </div>
    <%=f.error_span(:sizes) %>
  </div>
  <div class="form-group">
    <%= f.label "Цветове", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :colors_list, :class => 'form-control' %>
    </div>
    <%=f.error_span(:colors) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                shoes_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

calceus/app/views/shoes/edit.html.erb
<%- model_class = Shoe -%>
<div class="page-header">
  <h1>Редакция на обувки</h1>
</div>
<%= render :partial => 'form' %>

calceus/app/views/shoes/index.html.erb
<%- model_class = Shoe -%>
<div class="page-header.container">
  <h1>Обувки</h1>
  <%= link_to t('.new', :default => t("helpers.links.new")), new_shoe_path, :class => 'btn btn-primary' %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Модел</th>
      <th>Снимка</th>
      <th>Цена</th>
      <th>Вид</th>
      <th>Размери</th>
      <th>Цветове</th>
      <th>Дистрибутор</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @shoes.each do |shoe| %>
      <tr>
        <td><%= link_to shoe.title.mb_chars.upcase.to_s, shoe_path(shoe) %></td>
        <td><%= image_tag shoe.photo %></td>
        <td><%= shoe.price %></td>
        <td><%= shoe.gender %></td>
        <td><%= shoe.sizes_list %></td>
        <td><%= shoe.colors_list.mb_chars.downcase.to_s %></td>
        <td><%= link_to 'Купи', shoe.link %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_shoe_path(shoe), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      shoe_path(shoe),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Сигурни ли сте?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

calceus/app/views/shoes/new.html.erb
<%- model_class = Shoe -%>
<div class="page-header">
  <h1>Добавяне на обувки</h1>
</div>
<%= render :partial => 'form' %>

calceus/app/views/shoes/show.html.erb
<%- model_class = Shoe -%>
<div class="page-header">
  <h1>Обувки</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Модел:</strong></dt>
  <dd><%= @shoe.title.mb_chars.upcase.to_s %></dd>
  <dt><strong>Снимка:</strong></dt>
  <dd><%= image_tag @shoe.photo %></dd>
  <dt><strong>Цена:</strong></dt>
  <dd><%= @shoe.price %></dd>
  <dt><strong>Вид:</strong></dt>
  <dd><%= @shoe.gender %></dd>
  <dt><strong>Размери:</strong></dt>
  <dd><%= @shoe.sizes_list %></dd>
  <dt><strong>Цветове:</strong></dt>
  <dd><%= @shoe.colors_list.mb_chars.downcase.to_s %></dd>
  <dt><strong>Дистрибутор:</strong></dt>
  <dd><%= link_to 'Купи', @shoe.link %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              shoes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_shoe_path(@shoe), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              shoe_path(@shoe),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

<div class="page-header">
  <h1>Подобни</h1>
  <% unless @similar_shoes.empty? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Модел</th>
          <th>Снимка</th>
          <th>Цена</th>
          <th>Вид</th>
          <th>Размери</th>
          <th>Цветове</th>
          <th>Дистрибутор</th>
        </tr>
      </thead>
      <tbody>
        <% @similar_shoes.each do |shoe| %>
          <tr>
            <td><%= link_to shoe.title.mb_chars.upcase.to_s, shoe_path(shoe.id.to_s) %></td>
            <td><%= image_tag shoe.photo %></td>
            <td><%= shoe.price %></td>
            <td><%= shoe.gender %></td>
            <td><%= shoe.sizes.join(', ') %></td>
            <td><%= shoe.colors.join(', ').mb_chars.downcase.to_s %></td>
            <td><%= link_to 'Купи', shoe.link %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>Няма подобни обувки.</p>
  <% end %>
</div>